# value = +0o715
value = -0x1123_456_789
value2 = 1.124e9

# comment for explained
# second comment for explained
explained = true # third comment for explained

just_write_the_fucking_namespaces = true

dates_are_toml_like = 2025-11-22#L13:00:00+00:90 # and commentable

[section1]

keybinds = [ "ctrl shift alt      super   L",
             "mod  shift option-r command L" ]
            
table = {
    a = "AAA",
    b = { c = "DDD" }
}

multiline = """
some
text
""" 

= = 5

# mismatch = [ a = [ 5 ] ]
# 'quoted key' = 5
# warning = 'not a string
